---
sudo: required

services:
  - docker

language: java
jdk: openjdk11

before_install:
  - cp .maven.settings.xml $HOME/.m2/settings.xml
  - mvn fmt:check

script:
  - travis_wait mvn verify

after_success:
  - ./scripts/docker_push.sh

cache:
  directories:
    - $HOME/.m2

