---
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: mockcaseapiingress
spec:
  securityPolicy:
    name: "mockcaseapi-ingress"
---
apiVersion: v1
kind: Service
metadata:
  name: mockcaseapi
  annotations:
    beta.cloud.google.com/backend-config: '{"ports": {"http":"mockcaseapiingress"}}'
  labels:
    app: mockcaseapi
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    targetPort: http-server
  selector:
    app: mockcaseapi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mockcaseapiingress
  labels:
    app: mockcaseapi
  annotations:
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: mockcaseapi
    ingress.gcp.kubernetes.io/pre-shared-cert: mockcaseapi
spec:
  backend:
    serviceName: mockcaseapi
    servicePort: 80