apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mockcaseapi
  labels:
    app: mockcaseapi
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      name: mockcaseapi
      labels:
        app: mockcaseapi
    spec:
      containers:
      - name: mockcaseapi
        image: eu.gcr.io/census-int-ci/census-mock-case-api-service:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1000m"
            memory: "2048Mi"
          limits:
            cpu: "1000m"
            memory: "2048Mi"
        readinessProbe:
          httpGet:
            path: /info
            port: 8161
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /info
            port: 8161
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        ports:
        - name: http-server
          containerPort: 8161
        env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Dlogging.useJson=true
            -Dlogging.level.uk.gov.ons.ctp=DEBUG
            -Dlogging.level.org.springframework=WARN
            -Dendpoints.autoconfig.enabled=false-Dendpoints.beans.enabled=false
            -Dendpoints.configprops.enabled=false
            -Dendpoints.dump.enabled=false
            -Dendpoints.env.enabled=false
            -Dendpoints.metrics.enabled=false
            -Dendpoints.mapping.enabled=false
            -Dendpoints.shutdown.enabled=false
            -Dendpoints.trace.enabled=false
            -Dmanagement.health.rabbit.enabled=false"
        - name: RABBITMQ_USERNAME
          valueFrom:
            secretKeyRef:
              name: fs-rabbit-identity
              key: username
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fs-rabbit-identity
              key: password
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: mock-case-api-config
              key: rabbitmq-host
        - name: RABBITMQ_PORT
          valueFrom:
            configMapKeyRef:
              name: mock-case-api-config
              key: rabbitmq-port
        - name: SPRING_SECURITY_USER_NAME
          valueFrom:
            secretKeyRef:
              name: mock-case-api-identity
              key: username
        - name: SPRING_SECURITY_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mock-case-api-identity
              key: password
